TestSuite[{
	"Association.mt",
	"AssociationQ.mt",
	"Lookup.mt",
	"$linearBoxesToTeX.mt",
	"$cellStyleOptions.mt",
	"getBoxesToFormattedTeX.mt",
	"labelToKeyVal.mt",
	"processorDataLookup.mt",
	"extractCellOptionsProcessor.mt",
	"toInputFormProcessor.mt",
	"annotateSyntaxProcessor.mt",
	"mmaCellGraphicsProcessor.mt",
	"CellToTeX.mt"
}]