TestSuite[{
	"FirstCase.mt",
	"Association.mt",
	"AssociationQ.mt",
	"Lookup.mt",
	"$linearBoxesToTeX.mt",
	"$cellStyleOptions.mt",
	"boxesToString.mt",
	"labelToKeyVal.mt",
	"processorDataLookup.mt",
	"extractCellOptionsProcessor.mt",
	"toInputFormProcessor.mt",
	"annotateSyntaxProcessor.mt",
	"mmaCellGraphicsProcessor.mt",
	"CellToTeX.mt",
	"CellsToTeXPreamble.mt",
	"fullNotebooks.mt"
}]